const { onSchedule } = require("firebase-functions/v2/scheduler");
const { defineSecret } = require("firebase-functions/params");
const { getFirestore } = require("firebase-admin/firestore");
const OpenAI = require("openai");
const admin = require("firebase-admin");
const moment = require("moment-timezone");

const OPENAI_API_KEY = defineSecret("OPENAI_API_KEY");

// ✅ Only test times
const TEST_NOTIFICATION_TIMES = [
  "08:00",
  "08:15",
  "08:30",
  "08:45",
  "09:00",
  "09:15",
  "09:30",
  "09:45",
  "10:00",
  "10:15",
  "10:30",
  "10:45",
  "11:00",
  "11:15",
  "11:30",
  "11:45",
  "12:00",
  "12:15",
  "12:30",
  "12:45",
  "13:00",
  "13:15",
  "13:30",
  "13:45",
  "14:00",
  "14:15",
  "14:30",
  "14:45",
  "15:00",
  "15:15",
  "15:30",
  "15:45",
  "16:00",
  "16:15",
  "16:30",
  "16:45",
  "17:00",
  "17:15",
  "17:30",
  "17:45",
  "18:00",
  "18:15",
  "18:30",
  "18:45",
  "19:00",
  "19:15",
  "19:30",
  "19:45",
  "20:00",
  "20:15",
  "20:30",
  "20:45",
  "21:00",
  "21:15",
  "21:30",
  "21:45",
  "22:00",
];

// 🎨 Optional: load wallpapers (unchanged)
async function loadAllWallpapers(db) {
  try {
    const snap = await db
      .collection("wallpapers")
      .where("font_color", "==", "#f9f8f5")
      .get();
    const items = [];
    for (const doc of snap.docs) items.push({ ref: doc.ref });
    console.log(
      `🎨 Found ${items.length} wallpapers with font_color = #f9f8f5`,
    );
    return items;
  } catch (err) {
    console.error("❌ Failed to load filtered wallpapers:", err);
    return [];
  }
}

function pickRandom(arr) {
  if (!Array.isArray(arr) || arr.length === 0) return null;
  const idx = Math.floor(Math.random() * arr.length);
  return arr[idx];
}

// 🧠 Hardcoded prompt
const HARD_CODED_PROMPT = `
Write one short motivational message (1–2 sentences) that feels natural and human, as if written by a thoughtful person for social media.

It should sound modern, warm, and real — not like it was generated by AI. 
Avoid clichés, buzzwords, and any structure that feels scripted or promotional.

Focus on evoking a feeling of clarity, self-belief, or quiet motivation. 
Use conversational rhythm, simple language, and a personal tone that could fit on an Instagram caption or story.

No lists, no dashes, no markdown, no hashtags, no emojis.
Return only the message text.
`;

exports.createSocialMediaContentMessage = onSchedule(
  {
    schedule: "*/15 * * * *", // every 15 min
    secrets: [OPENAI_API_KEY],
  },
  async () => {
    console.log(
      "⏰ createSocialMediaContentMessage triggered at",
      new Date().toISOString(),
    );

    const TARGET_USER_ID = "abc"; //M0spoH9l7xQk9yO9r7MehaVT8Wl2
    const db = getFirestore();
    const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

    const invocationUtc = moment.utc();

    // Load target user
    const userDoc = await db.collection("users").doc(TARGET_USER_ID).get();
    if (!userDoc.exists) {
      console.warn(`⚠️ Target user ${TARGET_USER_ID} not found. Aborting.`);
      return;
    }
    const userRef = userDoc.ref;
    const userData = userDoc.data();
    const userTimezone = userData.timezone || "UTC";

    // Check if it's an allowed test time
    const nowLocal = invocationUtc.clone().tz(userTimezone);
    const currentSlot = nowLocal.format("HH:mm");
    if (!TEST_NOTIFICATION_TIMES.includes(currentSlot)) {
      console.log(`🕘 Not a test slot (${currentSlot}), skipping.`);
      return;
    }

    // Idempotency check
    const slotKey = nowLocal.format("YYYY-MM-DD_HH:mm");
    const ledgerId = `${TARGET_USER_ID}_${slotKey}`;
    const ledgerRef = db.collection("send_ledger").doc(ledgerId);
    const ledgerSnap = await ledgerRef.get();
    if (ledgerSnap.exists) {
      console.log(
        `↩️ Already sent for ${TARGET_USER_ID} @ ${slotKey}, skipping.`,
      );
      return;
    }

    // 🖼️ Load random wallpaper
    const wallpapers = await loadAllWallpapers(db);
    const pickedWallpaper = pickRandom(wallpapers);
    const selectedBackgroundRef = pickedWallpaper?.ref || null;

    // Generate message
    let contentText = "You are stronger than you think.";
    try {
      const resp = await client.responses.create({
        model: "gpt-4.1-2025-04-14",
        input: HARD_CODED_PROMPT,
        temperature: 1,
        top_p: 1,
      });
      const maybeText = (resp?.output_text || "").trim();
      if (maybeText) contentText = maybeText;
    } catch (err) {
      console.error(`❌ OpenAI error:`, err);
    }

    // Push notification
    try {
      await db.collection("ff_push_notifications").add({
        notification_title: "Become",
        notification_text: contentText,
        initial_page_name: "Quotes",
        notification_sound: "default",
        target_audience: "Individual",
        user_refs: `/${userRef.path}`,
        timestamp: admin.firestore.FieldValue.serverTimestamp(),
      });
      console.log(`📲 Notification created for ${userRef.id}`);
    } catch (err) {
      console.error(`❌ Failed to create notification:`, err);
    }

    // Save quote
    try {
      await db.collection("quotes").add({
        content: contentText,
        created_at: new Date(),
        user: userRef,
        is_favorited: false,
        is_public: false,
        is_approved: false,
        is_deleted: false,
        created_by: "createSocialMediaContentMessage",
        prompt_content: HARD_CODED_PROMPT,
        background_image: selectedBackgroundRef,
      });
      console.log(`✅ Quote saved for ${userRef.id}`);
    } catch (err) {
      console.error(`❌ Failed to save quote:`, err);
    }

    // Mark as sent
    try {
      await ledgerRef.set({
        user: userRef,
        slot: slotKey,
        created_at: admin.firestore.FieldValue.serverTimestamp(),
      });
    } catch (err) {
      console.error(`❌ Failed to mark ledger:`, err);
    }

    console.log("✅ createSocialMediaContentMessage completed.");
  },
);
